name: event_planner
description: A Flutter app to plan events with calendar and notifications.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
